language: node_js
node_js:
- 8
- node
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn commitlint --from="$TRAVIS_BRANCH" --to="$TRAVIS_COMMIT"
- yarn commitlint --from=$TRAVIS_COMMIT
- yarn test
after_script: greenkeeper-lockfile-upload
jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script: npx semantic-release@15
cache:
  yarn: true
branches:
  only:
  - master
  - next
  - "/^greenkeeper/.*$/"
  except:
  - /^v\d+\.\d+\.\d+$/
